general:
  kafka-topic: trader-updates

spring:
  kafka:
    producer:
      # Fixes the ClassCastException by converting Transaction objects to JSON
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: midas-core-group
      auto-offset-reset: earliest
      # Converts the incoming JSON back into a Transaction object
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.jpmc.midascore.foundation"

server:
  port: 33400